config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies, only: [:show, :index]
  resources :investments, only: [:create, :destroy]

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :investments
  has_many :users, through: :investments

  validates :name, presence: true, uniqueness: true

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  validates :user_id, presence: true, numericality: true
  validates :company_id, presence: true, numericality: true

  belongs_to :user
  belongs_to :company

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :investments
  has_many :companies, through: :investments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.order(name: :asc)
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @investment = Investment.create(user_id: current_user.id, company_id: params[:company_id])
    redirect_to root_path
  end

  def destroy
    @investment = current_user.investments.find(params[:id])
    @investment.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/companies/index.html.erb
<div class="bg-header">
  <div>
    <h1 id="tech-investor">TechInvestor</h1>
  </div>
</div>

<div class="about">
  <p><h1>Connecting investors to tech startups in the Austin, Texas area </h1></p>
</div>
<br>
<br>
<% if current_user %>

  <div class="row">
  <% @companies.each do |company| %>
    <div class="col-lg-2 company-name">
      <h4>
        <%= link_to company.name, company_path(company) %>
        <% if current_user %>
          <% investment = current_user.investments.find_by(company_id: company.id) %>
          <% if investment %>
            <%= link_to 'Divest', investment_path(investment), method: :delete, :class => "btn btn-primary" %>
          <% else %>
            <%= link_to 'Invest', investments_path(company_id: company.id), method: :post, :class => "btn btn-primary" %>
          <% end %>
        <% end %>
       </h4>
    </div>
  <% end %>
  </div>

<% else %>
  <div class="row">
  <% @companies.first(6).each do |company| %>
    <div class="col-lg-2 company-name">
        <%= link_to company.name, company_path(company) %>
        <% if current_user %>
          <% investment = current_user.investments.find_by(company_id: company.id) %>
          <% if investment %>
            <%= link_to 'Divest', investment_path(investment), method: :delete, :class => "btn" %>
          <% else %>
            <%= link_to 'Invest', investments_path(company_id: company.id), method: :post, :class => "btn" %>
          <% end %>
        <% end %>
    </div>
  <% end %>
</div>

<% end %>

app/views/companies/show.html.erb
<div class="logo">
   <%= image_tag(@company.logo, :class => "logo") %>

</div>

<div class="image_id">
<div class="row">
  <div class="col-md-12"><h1><%= link_to @company.name, @company.url %></h1>

</div>


</div>


<p id="bio">
  <%= @company.bio %>

</p>


</div>


<%= link_to "back", :companies %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href= "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel = "stylesheet">

  <title>TechInvestor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>

<div class="container">

  <ul class="nav nav-pills navbar-static-top">
    <li role="presentation" class="active"><a href='/'>Home</a></li>
      <% if !current_user %>
        <li role="presentation"><%= link_to 'Sign-up', new_user_registration_path %></li>
        <li role="presentation"><%= link_to 'Login', new_user_session_path %></li>
      <% else %>
        <li role="presentation"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% end %>
  </ul>

  <%= yield %>
</div>

</body>
</html>